#!/usr/bin/env bash
# install nginx on remote server

apt-get update
apt-get upgrade
apt-get install -y nginx
mkdir /var/www/nginx/html
touch /var/www/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.html

