#!/usr/bin/env bash
# install nginx on remote server

apt-get update
apt-get install -y nginx
rm /var/www/html*.html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /var/www/html;
    index   index.html;
}" > /etc/nginx/sites-available/default
service nginx restart