#!/usr/bin/env bash
#displays best school 10 times 
i=1
while [ $i -le 10 ]

do 
       if [ $i = 9 ]
       then 
        echo "Best School
hi"
   
        else 
          echo "Best School"
          fi 
           ((i++))
   done 
  export i 
