#!/usr/bin/env bash
#this script will display best school ten times , other  4 and 8
i=1 

  while [ $i -le 10 ]
	  
  do

  if [ $i = 4 ]
  then 
	  echo "bad luck"
  

  elif [ $i = 8 ]
  then 
	  echo "good luck"
else 
	echo "Best School"

  fi
  ((i++))
done
export i
