#!/usr/bin/env bash
#this script will number 1-20

i=1 
while [ $i -le 20 ]
do	
  if [ $i = 4 ]
  then
      echo "$i
bad luck from China"
    elif [ $i = 9 ]
    then 
       echo "$i
bad luck from Japan"
    elif [ $i = 17 ]
    then 
     echo "$i
bad luck from Italy"
    else 
     echo "$i"
  fi
       ((i++))
done
