#!/usr/bin/env bash
# install nginx on remote server
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
#sudo ufw allow 'Nginx HTTP'
mkdir -p /etc/nginx/html/
sudo touch /etc/nginx/html/index.html /etc/nginx/html/404.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
sudo  echo  "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 http://gavintobin.tech/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart

